UCLALibrary/fester

.gitignore
.travis.yml
LICENSE.txt
pom.xml
src/main/java/edu/ucla/library/iiif/manifeststore/Config.java
src/main/java/edu/ucla/library/iiif/manifeststore/Constants.java
src/main/java/edu/ucla/library/iiif/manifeststore/HTTP.java
src/main/java/edu/ucla/library/iiif/manifeststore/Op.java
src/main/java/edu/ucla/library/iiif/manifeststore/handlers/GetPingHandler.java
src/main/java/edu/ucla/library/iiif/manifeststore/verticles/MainVerticle.java
src/main/resources/checkstyle.xml
src/main/resources/logback.xml
src/main/resources/manifeststore.yaml
src/main/resources/manifeststore_messages.xml
src/test/java/edu/ucla/library/iiif/manifeststore/verticles/MainVerticleTest.java
src/test/resources/logback-test.xml
src/test/resources/settings.xml
src/test/resources/test-config.properties
src/test/scripts/post-it-shutdown.sh
src/test/scripts/pre-it-startup.sh

* Add baseline project code
* Add stub .travis.yml
* Add stub OpenAPI config
* Add baseline IT setup
* Use checkstyle config from jp2-bucketeer

[IIIF-121] Add baseline project code

---

.travis.yml
src/main/resources/manifeststore.yaml

* Add manifest store endpoint and actions
* Add HTTP response codes and messages
* Validated the spec using OpenAPI validator: https://github.com/p1c2u/openapi-spec-validator

[IIIF-118] add openapi spec

---

.travis.yml
src/main/resources/manifeststore.yaml
src/test/java/edu/ucla/library/iiif/manifeststore/handlers/DeleteManifestHandlerTest.java
src/test/java/edu/ucla/library/iiif/manifeststore/handlers/GetManifestHandlerTest.java
src/test/java/edu/ucla/library/iiif/manifeststore/handlers/PutManifestHandlerTest.java

* Update the OpenAPI spec to match patterns described in IIIF-270
* Updated tests to match the new endpoint URLs

Iiif 281 update open api spec

---

README.md
src/main/resources/logback.xml

* Add snyk and travis badges
* Add line numbers to output logging

Add badges

---

pom.xml

* borrow configuration from the work on IIF-258, which is a corresponding ticket for Bucketeer.

[IIIF-259] configure maven enforcer plugin to require Java 11

---

README.md

grumble, grumble... the eternal travis migration... grumble, grumble

Fix typo: travis.org vs. travis.com

---

pom.xml

Update transitive dependency for security reasons.

[IIIF-317] Update dependency

---

.gitignore
README.md
pom.xml
src/main/java/edu/ucla/library/iiif/manifeststore/Constants.java
src/main/java/edu/ucla/library/iiif/manifeststore/handlers/DeleteManifestHandler.java
src/main/java/edu/ucla/library/iiif/manifeststore/handlers/GetManifestHandler.java
src/main/java/edu/ucla/library/iiif/manifeststore/handlers/PutManifestHandler.java
src/test/java/edu/ucla/library/iiif/manifeststore/handlers/AbstractManifestHandlerTest.java
src/test/java/edu/ucla/library/iiif/manifeststore/handlers/DeleteManifestHandlerTest.java
src/test/java/edu/ucla/library/iiif/manifeststore/handlers/GetManifestHandlerTest.java
src/test/java/edu/ucla/library/iiif/manifeststore/handlers/PutManifestHandlerTest.java

* Add support for json-less IDs
* Add tests for json-less IDs
* Add a live testing environment for devs to use
* Add native library extensions for netty for improved performance

IIIF-341 Support IDs without .json extensions

---

src/main/java/edu/ucla/library/iiif/manifeststore/Constants.java
src/main/resources/manifeststore.yaml
src/main/resources/manifeststore_messages.xml
src/test/java/edu/ucla/library/manifeststore/ManifestUploadIT.java
src/test/resources/logback-test.xml

Ensure the round trip works for Manifest-store:
* POST a doc
* GET it back
* DELETE it

[IIfIF-350] :white_check_mark: Add integration test for manifest store

---

README.md
src/main/java/edu/ucla/library/iiif/manifeststore/Op.java
src/main/java/edu/ucla/library/iiif/manifeststore/handlers/GetStatusHandler.java
src/main/java/edu/ucla/library/iiif/manifeststore/verticles/MainVerticle.java
src/main/resources/manifeststore.yaml
src/test/java/edu/ucla/library/iiif/manifeststore/verticles/MainVerticleTest.java
src/test/java/edu/ucla/library/manifeststore/ManifestUploadIT.java

* Revise the Manifest-store spec to change the ping endpoint
* Revise the the Manifest-store docs to reflect this change
* Revise the tests will be changed to use the new endpoint

[IIIF-478] refactor /ping to /status/manifest-store

---

.travis.yml

Wrong repostiory, this one does not push to dockerhub, the docker-fester repo does.

[IIIF-532] revert PR29, this repo doesn't push to dockerhub

---

src/main/scripts/festerize/README.md
src/main/scripts/festerize/festerize.py

* Add option for IIIF-host to festerize script
* address some minor path issues
* update readme

[IIIF-592] Add option for iiif-host to festerize script, address some minor path issues, update readme.

---

pom.xml

:writing_hand: :heavy_check_mark:

add markmatney to authors

---

src/main/java/edu/ucla/library/iiif/fester/CSV.java
src/main/java/edu/ucla/library/iiif/fester/Constants.java
src/main/java/edu/ucla/library/iiif/fester/CsvHeaders.java
src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java

[IIIF-716] Add repository name, local rights statement, and rights contact metadata to manifests

---

README.md
src/test/scripts/git-hooks/pre-push

[IIIF-634] Add pre-push Git hook to prevent pushing commits that break the build

---

pom.xml
src/main/resources/logging.properties

To test, create or modify `~/.aws/config` with something like:
```
[profile iiif_802]
region = us-west-1
output = json
```
and then run `mvn clean test`.

[IIIF-802] Suppress warnings from AWS SDK during Maven build

---

src/main/scripts/festerize/README.md
src/main/scripts/festerize/festerize.py
src/main/scripts/festerize/install.sh
src/main/scripts/festerize/setup.py

[IIIF-803] Add procedure for installing Festerize with Pip

---

README.md

Not associated with a ticket, but just a small update to the badge URL.

Fix Fester Snyk badge URL

---

src/test/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticleTest.java

* Fix assertions so they come from the vertx-unit context
* Add exception handling around reading from test fixtures

[IIIF-772] Add better error handling in test

---

pom.xml
src/test/java/edu/ucla/library/iiif/fester/utils/ContainerUtils.java

* Turn on JDK linting
* Add wildcard to creation of GenericContainer ContainerUtils

[IIIF-772] Fix unchecked type warning

---

src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
src/main/resources/fester_messages.xml

* Add additional logging to see status code and response time
* Add error handling on the S3BucketVerticle GET
* Minor code style tweaks

[IIIF-851] Add error handler for S3BucketVerticle GET

---

pom.xml
src/main/java/edu/ucla/library/iiif/fester/CsvHeaders.java
src/main/java/edu/ucla/library/iiif/fester/CsvParser.java
src/main/java/edu/ucla/library/iiif/fester/LockedManifest.java
src/main/java/edu/ucla/library/iiif/fester/handlers/EndpointConfigHandler.java
src/main/java/edu/ucla/library/iiif/fester/utils/IDUtils.java
src/main/java/edu/ucla/library/iiif/fester/utils/ItemSequenceComparator.java
src/main/java/edu/ucla/library/iiif/fester/verticles/MainVerticle.java
src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
src/test/java/edu/ucla/library/iiif/fester/fit/PagesManifestFT.java
src/test/java/edu/ucla/library/iiif/fester/utils/ContainerConfig.java
src/test/java/edu/ucla/library/iiif/fester/utils/ContainerUtils.java
src/test/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticleTest.java

* Update dependencies for security fix
* Update to newest version of s3 library
* Update parent project in POM
* Add missing Javadocs (caught by updated Checkstyle rules)
* Update deprecated methods as a result of vert.x version upgrade
* Fix NPE in test container config (that happened when running build without the feature-flag tests)

[IIIF-847] Update dependencies

---

README.md
src/main/scripts/festerize/README.md
src/main/scripts/festerize/festerize.py

This incorporates changes we've discussed in Jira, and in #115 and #119.

[IIIF-828] Improve Festerize and Fester description

---

src/main/java/edu/ucla/library/iiif/fester/Status.java
src/main/java/edu/ucla/library/iiif/fester/handlers/GetStatusHandler.java

[IIIF-872] code and constants for memory warning

---

src/main/java/edu/ucla/library/iiif/fester/Status.java
src/main/java/edu/ucla/library/iiif/fester/handlers/GetStatusHandler.java
src/main/resources/fester.yaml

* Added the `iiif-version` variable to the `requestBody` element of `/collections`
* Used `enum` to specify legal values for new variable

[Iiif 868] adding variable to OpenAPI spec

---

src/main/java/edu/ucla/library/iiif/fester/Op.java
src/main/java/edu/ucla/library/iiif/fester/Status.java
src/main/java/edu/ucla/library/iiif/fester/handlers/CheckEndpointsHandler.java
src/main/java/edu/ucla/library/iiif/fester/handlers/EndpointConfigHandler.java
src/main/resources/fester.yaml
src/main/resources/fester_messages.xml

Updates: 
- Created CheckEndpointsHandler.java to execute calls against S3 and report HTTP response codes/status
- Modified Status.java to add constants used by CheckEndpointsHandler
- Modified Op.java to add endpoint constant for CheckEndpointsHandler
- Modified EndpointConfigHandler.java to add the CheckEndpointsHandler endpoint
- Modified fester.yaml to publish the URL for CheckEndpointsHandler
- Added S3 endpoint messages to fester_messages.xml

[IIIf-906] Update Fester status endpoint to provide a better healthcheck: S3 Endpoints

---

README.md
pom.xml

Add information about system prerequisites that are required to build Fester.

[IIIF-895] Update README

---

pom.xml
src/test/java/edu/ucla/library/iiif/fester/fit/PagesManifestFT.java

Update two dependencies. The output can be checked by running this script locally on this branch: https://gist.github.com/ksclarke/18fa628d80a05411a4e6f958ba74cdc8

[IIIF-903] Update Fester dependencies

---

pom.xml
src/main/resources/fester_messages.xml
src/test/java/edu/ucla/library/iiif/fester/handlers/CheckEndpointsHandlerTest.java

Updates:
- Added CheckEndpointsHandlerTest.java
- Added debug message to fester_messages.xml

[IIIF-915] Add Unit Test for CheckEndpointsHandler
