- src/main/java/edu/ucla/library/iiif/manifeststore/Op.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/AbstractManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/DeleteManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/GetManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/PostManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/PutManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/verticles/MainVerticle.java
- src/main/resources/manifeststore_messages.xml
This just connects the OpenAPI spec created in IIIF-118 to the router created in IIIF-121. I've added stubs for the handlers (that each have their own tickets) and created an abstract class to abstract away the S3 communications from the individual handlers (this will be fleshed out with the handlers tickets).
> [IIIF-119] Configure router with OpenAPI spec

- README.md
- pom.xml
- src/main/java/edu/ucla/library/iiif/manifeststore/Constants.java
- src/main/java/edu/ucla/library/iiif/manifeststore/HTTP.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/AbstractManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/DeleteManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/GetManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/PostManifestHandler.java
- src/main/java/edu/ucla/library/iiif/manifeststore/handlers/PutManifestHandler.java
- src/main/resources/manifeststore.yaml
- src/main/resources/manifeststore_messages.xml
- src/test/java/edu/ucla/library/iiif/manifeststore/handlers/AbstractManifestHandlerTest.java
- src/test/java/edu/ucla/library/iiif/manifeststore/handlers/DeleteManifestHandlerTest.java
- src/test/java/edu/ucla/library/iiif/manifeststore/handlers/GetManifestHandlerTest.java
- src/test/resources/testManifest.json
* Add manifest GET handler
* Add manifest DELETE handler
* Add GetManifestHandlerTest
* Add DeleteManifestHandlerTest
* Add abstract handler and test classes that other handlers and their tests can extend
* Update OpenAPI spec to have delete return 204 instead of 200 (because that's what S3 uses)
This ticket addresses IIIF-240 and IIIF-242.
> [IIIF-240] Add get and delete handlers

- pom.xml
- src/main/java/edu/ucla/library/iiif/manifeststore/verticles/MainVerticle.java
- src/main/resources/manifeststore.yaml
- src/main/webroot/index.html
This adds a route to serve the API docs up at: /docs/manifest-store/
> [IIIF-279] Add docs view to app

- .travis.yml
Correct typo for dockerhub repo name for fester (uclalibrary/fester not uclalibrary/docker-fester)
> [IIIF-532] Use correct repo name for fester on dockerhub

- pom.xml
- src/main/java/edu/ucla/library/iiif/fester/Config.java
- src/main/java/edu/ucla/library/iiif/fester/Constants.java
- src/main/java/edu/ucla/library/iiif/fester/Op.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/MainVerticle.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
- src/main/resources/fester_messages.xml
- src/test/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticleTest.java
- Remove the ResultsMap and other image-related things from the
Bucketeer S3BucketVerticle
- Refactor the message requirements for the S3BucketVerticle to work
with a JSON object
- Refactor the test for the S3BucketVerticle to send a manifest instead
of an image
- Bump the version of Vert-X we're using
> [IIIF-507] Borrow the S3BucketVerticle from Bucketeer, adjust for Fester

- src/main/java/edu/ucla/library/iiif/fester/verticles/MainVerticle.java
Fix the display of the OpenAPI docs by changing the path matching pattern and setting a default index page.
> Fix display of OpenAPI specs

- src/main/java/edu/ucla/library/iiif/fester/handlers/AbstractManifestHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/PostCsvHandler.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/PostCsvHandlerTest.java
This is an incremental step towards returning a CSV which includes the URLs for the created manifests. Taking this small step lets our upload script get CSVs and handle them like it should.
> Add CSV response to PostCsv endpoint

- src/main/java/edu/ucla/library/iiif/fester/Constants.java
- src/main/java/edu/ucla/library/iiif/fester/ImageInfo.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/PostCsvHandler.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
- src/main/resources/fester.yaml
- src/test/java/edu/ucla/library/iiif/fester/handlers/PostCsvHandlerTest.java
Currently, Fester creates manifests using the IIIF server its been configured with. We want it to be able to generate manifests that will point to a different IIIF server (e.g., Sinai) too though. This PR adds the ability to pass a `iiif-host` parameter to the PostCsv endpoint so that CSVs supplied with that different IIIF host will produce manifests whose manifest links point to Fester and whose IIIF links point to the different IIIF server.
> [IIIF-591] Support using a different IIIF host for manifest creation

- src/main/java/edu/ucla/library/iiif/fester/CsvMetadata.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
- src/main/resources/fester_messages.xml
- src/test/java/edu/ucla/library/iiif/fester/verticles/FakeS3BucketVerticle.java
- src/test/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticleTest.java
- src/test/resources/json/ark%3A%2F21198%2Fzz0009gv8j.json
* Refactor to reduce nesting levels in ManifestVerticle
* Add a CsvMetadata class to reduce the number of variables passed around in ManifestVerticle
* Add handling for page-only CSV inputs to the manifest generation batch process
* Get rid of the zero in `aMessage.fail(0, message);` so there is a specific fail int code, even if it's just a generic one used for passing through a throwable's message
Fixes #IIIF-593 too
> [IIIF-580] Handle page-only CSV inputs

- src/main/java/edu/ucla/library/iiif/fester/CSV.java
- src/main/java/edu/ucla/library/iiif/fester/CsvHeaders.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
We used Project Name for the collection doc label, but after trying to run our first real Sinai CSV and talking with Dawn, we're going to change to using Title for the collection doc label value. This also reduces the number of column headers we care about in the CSV. I'm creating a separate ticket for documenting those (in the script, openapi, etc.)
> [IIIF-600] Change collection doc's label source

- src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
- src/main/resources/fester_messages.xml
Oops, our manifests are stored in the S3 bucket with a ".json" extension but the batch handler's S3 GET was forgetting to add that to the ID being retrieved.
> Fix S3 manifest lookup (missing ext)

- .gitignore
- src/main/java/edu/ucla/library/iiif/fester/ImageInfoLookup.java
- src/main/resources/fester_messages.xml
- src/main/resources/logback.xml
* Fix the production log location (doesn't affect log location when running in test mode)
* Increase the read timeout when looking for w/h from info.json in Cantaloupe
* Ignore the output directory festerize creates if it's run from the project's root directory
* Make the fallback w/h if image can't be found 1 (a workaround for issue with presentation library)
> [IIIF-618] Fix timeout issue on image w/h lookup

- pom.xml
- src/main/java/edu/ucla/library/iiif/fester/ImageInfoLookup.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
- src/main/resources/fester_messages.xml
* Log a warning when we set the w/h to a default value; this isn't an error but we shouldn't blindly do it
* Add the w/h "set to 1 instead of 0" workaround to one other place that's another on-error fallback
> [IIIF-618] Add log warning and one more default value workaround

- src/main/java/edu/ucla/library/iiif/fester/verticles/MainVerticle.java
- src/main/resources/fester_messages.xml
- src/test/java/edu/ucla/library/iiif/fester/handlers/DeleteManifestHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/GetManifestHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/PostCsvHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/PutManifestHandlerTest.java
- Set a custom BodyHandler on PostCsvHandler that ensures uploaded files are eventually deleted from disk
- Remove some redundant annotations on the handler test classes
(PostCsvHandlerTest has even more repeated code now, so it should be refactored at some point.)
>  [IIIF-616] Delete uploaded CSV files after PostCsvHandler sends a response

- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
Fix typo that caused a RuntimeException to be thrown when a work's Title value wasn't a valid viewingHint.
> [IIIF-649] Fix typo bug

- pom.xml
- src/main/resources/checkstyle.xml
- src/main/resources/fester.yaml
- src/test/java/edu/ucla/library/iiif/fester/it/ManifestUploadIT.java
- src/test/scripts/post-it-shutdown.sh
- src/test/scripts/pre-it-startup.sh
* Update version of the parent project to pull in the latest and greatest conveniences
* Update freelib-utils to the split freelib-utils/freelib-maven-plugins versions to reduce output Jar size
* Update IT script to give the application a little more time to start before IT tests are run against it
* Update Fester API version in the OpenAPI documentation/spec
* Removed Jacoco plugin because that's now handled by a profile in the parent project
> [IIIF-632] Update freelib dependency versions

- pom.xml
The old xml-maven-plugin we were using couldn't check the well-formedness of XML files without also trying to validate them (our XML files don't have schemas so our builds had misleading WARNING messages). In this PR we switch to a XML file checking plugin that can check well-formedness.
> [IIIF-597] Check well-formedness of project's XML files

- src/main/java/edu/ucla/library/iiif/fester/Constants.java
- src/main/java/edu/ucla/library/iiif/fester/utils/IDUtils.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/AbstractFesterHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/PutManifestHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/utils/IDUtilsTest.java
- src/test/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticleTest.java
- prefix work manifest S3 keys with "works/"
- add TODOs for better checking of resource types in the future (didn't attempt to fix now since would require callers of those IDUtils methods to handle exceptions thrown by them)
> [IIIF-589] Put work manifests in a "works" directory inside S3 bucket

- src/main/java/edu/ucla/library/iiif/fester/ImageInfoLookup.java
- src/main/java/edu/ucla/library/iiif/fester/ImageNotFoundException.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
- src/main/resources/fester_messages.xml
Image w/h lookups were failing despite us having a fallback mechanism in place for supplying a w/h that's a "good enough" guess. This is happening because Cantaloupe returns a 403 response code for an image that can't be found in S3 (and we're checking for a 404). This PR treats 403s from Cantaloupe like they were 404s. It also renames ManifestNotFoundException to ImageNotFoundException because it's actually an image that can't be found, not a manifest.
> [IIIF-690] Work around Cantaloupe returning a 403 for a 404 image

- pom.xml
- src/main/resources/fester.yaml
- src/main/webroot/index.html
* Add actual version number to POM in preparation for doing deployments through Maven
* Filter the fester.yaml OpenAPI spec file in the Maven build process, adding version to it
* Change the Maven phase of the webroot population to catch the newly filtered file
* Change the location of the fester.yaml that the webroot population uses to use newly filtered file
* Fix the "API documentation" link in the HTML page to correctly point to the documentation
* Move the implemented collection GET to the "Implemented" tag, leaving just PUT and DELETE as "Proposed"
> [IIIF-698] Update generated API documentation

- pom.xml
- src/main/java/edu/ucla/library/iiif/fester/Constants.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/AbstractFesterHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/GetCollectionHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/PostCsvHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/PutCollectionHandler.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/AbstractFesterVerticle.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/MainVerticle.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
- src/main/resources/fester.yaml
- src/main/resources/fester_messages.xml
- src/test/java/edu/ucla/library/iiif/fester/handlers/PutCollectionHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/it/ManifestUploadIT.java
- src/test/java/edu/ucla/library/iiif/fester/verticles/FakeS3BucketVerticle.java
- src/test/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticleTest.java
- src/test/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticleTest.java
In addition to the notes in the commits:
- I removed `AbstractFesterVerticle.getS3Manifest` (since it was only being called once) and replaced the call to it with the more generic `sendMessage`, but I'm not super opinionated on removing it if it's deemed useful.
- `FakeS3BucketVerticle`'s `JSON_FILES` is now mutable, so that it supports PUT.
- Note: all that's really going on at `@@ -92,72 +92,86 @@ public void start(final Promise<Void> aPromise) {` in the diff for `ManifestVerticle` is a change in indentation, since that code block is now inside a switch statement.
> [IIIF-644] Implement PUT for collection docs

- README.md
- pom.xml
- src/main/java/edu/ucla/library/iiif/fester/verticles/MainVerticle.java
- src/main/webroot/css/fester-custom.css
- src/main/webroot/docs/index.html
- src/main/webroot/error.html
- src/main/webroot/javascripts/redoc-config.js
- src/main/webroot/success.html
- src/main/webroot/upload/css/upload-custom.css
- src/main/webroot/upload/csv/index.html
I learned the debugging mode isn't compatible with the automatic reloading of resources in the vertx-maven-plugin so I added an additional profile. There is now one for debugging and one for live testing.
* Updated the paths for served HTML pages (@cachemeoutside will need to update the /docs links in the load balancer)
* Added an HTML form that submits an uploaded CSV file to the Fester service and returns an updated CSV file to the browser
* Updated some of the site's CSS stylings (minor changes)
> [IIIF-727] Add Fester ingest form

- .travis.yml
With the new Docker test stuff, the Maven log gets longer than Travis' max log length. This PR is to make the Maven log output a little less voluminous.
> [IIIF-764] Reduce log output in Travis build

- src/main/webroot/css/redoc-custom.css
Push the anchor headers down so that they do not display underneath the top menu bar (when someone clicks on them to go to the anchor location).
I added "before" and "after" screenshots to the Jira issue for this.
> [IIIF-707] Update CSS to fix text under top bar

- .travis.yml
With the new release mechanism, we base Docker image tags on the version in the POM rather than on the version in the GitHub tag, so we don't need to run Travis on tag branches anymore. Doing so causes an extra unnecessary Travis run.
> [IIIF-770] Fix double release build

- pom.xml
TestContainers seems to leave networks around despite Ryuk supposedly being responsible for cleaning them up. We add an additional cleanup as a part of our build so we don't get to the point where all Docker's networks are used up and we can't run the build.
> [IIIF-788] Clean up obsolete Docker networks

- src/main/java/edu/ucla/library/iiif/fester/Constants.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/DeleteManifestHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/GetCollectionHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/GetManifestHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/GetStatusHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/MatchingOpNotFoundHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/PutCollectionHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/PutManifestHandler.java
- src/main/resources/fester.yaml
- src/main/resources/fester_messages.xml
- src/test/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticleTest.java
* Add human friendly text to the responses of our endpoints (that don't already output something like HTML that's intended for the user)
* Minor refactor on a variable name for consistency on naming standards
* Bump up the timeout on one of the tests that fails periodically because the S3BucketVerticle/FakeS3BucketVerticle swap doesn't happen in a timely manner
* Update OpenAPI spec with response content types and examples
> [IIIF-464] Add human friendly responses to endpoints

- src/main/resources/fester.yaml
We apparently missed including a 404 response in the delete manifest endpoint in the OpenAPI spec. We implemented it in the handler and have a test for it, but no documentation in the spec. This ticket adds it to the spec/documentation.
> [IIIF-800] Add 404 to manifest delete endpoint in spec

- src/main/java/edu/ucla/library/iiif/fester/MalformedPathException.java
- src/main/java/edu/ucla/library/iiif/fester/utils/IDUtils.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
- src/main/resources/fester_messages.xml
- src/test/java/edu/ucla/library/iiif/fester/utils/IDUtilsTest.java
* Create new runtime exception for path (s3 or URI) problems
* Catch more possible (bad) variations in ID values
* Add new tests for those error checks
* Refactor tests for brevity
This PR is going to have conflicts with the one that removed the deprecated method from IDUtils, I fear.
> [IIIF-697] Improve error handling in IDUtils

- .gitignore
- README.md
- pom.xml
- src/main/resources/logback.xml
- src/test/java/edu/ucla/library/iiif/fester/handlers/AbstractFesterHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/GetCollectionHandlerTest.java
- src/test/java/edu/ucla/library/iiif/fester/handlers/PutCollectionHandlerTest.java
- src/test/resources/logback-test.xml
* Set test logging to a sane level (i.e., ERROR instead of DEBUG)
* Allow overriding default test stdout logging level with Maven build property (via command line or settings.xml file)
* Create mechanism to override `src/test/resources/logback-test.xml` with `logback-test.xml` file in project's root directory (and add that file to `.gitignore`) for even more control over logging levels
* Turn off error logging on tests that are supposed to test failures (in these cases, the ERROR logs are false positives)
* Update README
Fixes IIIF-784 (log to file) and IIIF-778 (have more control over logging levels)
> [IIIF-784] Update test logging config and options

- README.md
- pom.xml
* Fix the maven-exec-plugin configuration to have the Docker network cleanup only happen when the pre-integration phase is run.
* Update release documentation in the README
* Bump the POM version for the next release, while we're here editing things.
> [IIIF-808] Fix release deployment

- src/main/java/edu/ucla/library/iiif/fester/ImageInfoLookup.java
Now, just logs the URL that failed.
> [IIIF-810] Fix ImageInfoLookup error handling

- src/main/scripts/festerize/README.md
A small reformat to prevent the install command from being hidden by the README code scroller.
> Reformat festerize README.md

- README.md
- pom.xml
- src/main/docker/Dockerfile
- src/main/java/edu/ucla/library/iiif/fester/Config.java
- src/test/java/edu/ucla/library/iiif/fester/utils/ContainerUtils.java
To test, set a few breakpoints in the application code and in the test suite code (particularly an FT, FfT, or IT), and then follow the setup instructions in the README to run the debugger and verify that execution suspends at the breakpoints.
Note that the `debug` Maven profile is now used for debugging the test suite, and `runDebug` is for running a Fester instance in "debug" mode.
> [IIIF-782] Enable debugging of application code running in a container

- src/main/webroot/upload/csv/index.html
Update CSV upload form's default IIIF host URL to include the `/iiif/2` Cantaloupe path.
> Update IIIF host default in CSV upload form

- pom.xml
This pulls in changes made in the upstream library. Those changes can be seen at:
https://github.com/ksclarke/jiiify-presentation/commit/5c4939c2fc391ae5e4ba18df2b43564bf09e7a79
They include: 1) updating the jiiify-presentation parent project version, 2) updating Javadocs that the new parent project Checkstyle rules said needed to be updated, 3) updating the project's pmd-rules configuration, and 3) specifying an order of manifest properties that should be used on serialization. A simple test is included to confirm that viewingHint and viewingDirection's serialization orders have been fixed and existing test fixtures were updated as well.
> [IIIF-843] Update manifest serialization order

- pom.xml
- src/main/docker/configs/fester.properties.default
- src/main/java/edu/ucla/library/iiif/fester/Constants.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/AbstractFesterHandler.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/DeleteManifestHandler.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/S3BucketVerticle.java
- src/main/resources/fester_messages.xml
The previous PR didn't completely fix the issue. There is also an upstream bug with the v4 signature generation. This works around that.
* Update endpoint references
* Fallback to v2 signing because there is a bug with v4 signing and S3 regions in the upstream library
* Simplify some of the S3Client construction (the upsteam library does more parsing of endpoint now)
* Add additional debug logging
> [IIIF-867] slight return

- src/main/java/edu/ucla/library/iiif/fester/ManifestNotFoundException.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
- src/main/resources/fester_messages.xml
- src/main/scripts/festerize/festerize.py
- src/main/scripts/festerize/setup.py
- src/main/webroot/error.html
- src/test/java/edu/ucla/library/iiif/fester/fit/PostCsvFIT.java
- if `getLockedManifest` fails to retrieve a manifest, send the ARK and the manifest type back to the client
- assign an id to the error message HTML tag
- on the client running `festerize`, only log the error message, not the entire HTML response
> [IIIF-863] Improve "manifest not found" error message

- CODEOWNERS
- pom.xml
- src/test/java/edu/ucla/library/iiif/fester/fit/PagesManifestFT.java
* Update POM/parent project
* Remove obsolete Codacy configuration (it's done by the parent POM/project now)
* Change to running tests in a single fork instead of the same process so that the JaCoCo plugin will run
* Add CODEOWNERS file so we'll get auto-added as reviewers on PRs
> Update POM for Codacy integration fix

- pom.xml
- src/main/docker/Dockerfile
- src/main/java/edu/ucla/library/iiif/fester/Constants.java
- src/main/java/edu/ucla/library/iiif/fester/handlers/PostCsvHandler.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
- src/main/java/edu/ucla/library/iiif/fester/verticles/V2ManifestVerticle.java
- src/main/resources/fester_messages.xml
- src/test/java/edu/ucla/library/iiif/fester/fit/BaseFesterFT.java
- src/test/java/edu/ucla/library/iiif/fester/fit/PagesManifestFT.java
- src/test/java/edu/ucla/library/iiif/fester/fit/PostCsvFIT.java
- src/test/resources/json/ark%3A%2F21198%2Fzz0009gsq9.json
* Update some POM dependencies to fix an S3 test problem.
* Update obsolete curl version in the Dockerfile.
* Remove obsolete codacy plugin config (this has been done on main already but this branch needs it removed too in order to pass the Codacy check).
* Add some exclusions to the shade plugin config to remove warning messages.
* Add content-disposition to PostCsvHandler's response so downloaded file has the same name as the uploaded file.
* Fix v2 manifest creator so that it creates manifest references in the collection (this information was being sent to the v2 manifest verticle, but I neglected to do anything with it when creating the manifest).
* Extended the timeout on one of the tests since my new laptop is slower than the last and sometimes times out (side comment: we really …
> [IIIF-953] Fix v2 verticle so it adds works to collection
